---

- name: Notify Slack that VolumeSnapshot has been created
  community.general.slack:
    token: "{{ token }}"
    msg: |
        #### VolumeSnapshot created within {{ my_namespace }} my_namespace ####
        ----------------------------------------------------
        Namespace: {{ my_namespace }}

        View your volume snapshots via
        oc get volumesnapshot -n {{ my_namespace }}

        Need Assistance?
        <https://example.com|Open a ticket>
        ----------------------------------------------------
    channel: '#ansiblefest-demo'
    color: good
    username: 'AnsibleFest-bot'
    link_names: 0
    parse: 'none'
