---
- name: Install AWS
  hosts: localhost
  collections:
    - amazon.aws
  tasks:   
    - name: Download aws cli
      ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/usr/local/bin/awscliv2.zip"
        mode: 755
      become_user: root

    - name: Unzip installer
      ansible.builtin.unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Get aws version
      ansible.builtin.shell: /tmp/aws --version
      register: aws

    - name: Debugging
      ansible.builtin.debug: 
        var: aws
