---

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "t2.small"
  when: vm_choice == "small (1 vCPU, 2 GiB Memory)"

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "t2.medium"
  when: vm_choice == "medium (2 vCPU, 4 GiB Memory)"

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "m4.large"
  when: vm_choice == "large (2 vCPU, 8 GiB Memory)"

- name: Launch an AWS EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ my_name }}"
    key_name: "{{ key }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    region: "{{ region }}"
    security_group: "{{ security_group }}"
    wait: yes
    volumes:
    - device_name: "{{ device_name }}"
      ebs:
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
    tags:
      Name: "{{ my_name }}"
      owner: "{{ owner }}"
      sleep_schedule: "{{ sleep_schedule }}"
    vpc_subnet_id: "{{ subnet_id }}"
    network:
      assign_public_ip: no
  register: ec2_details

- name: Debug info ec2 instance
  debug:
    var: ec2_details
