---
- name: Launch an AWS EC2 instance
  amazon.aws.ec2:
    key_name: "{{ key }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    group_id: "{{ security_group }}"
    wait: yes
    volumes:
    - device_name: "{{ device_name }}"
      volume_type: "{{ volume_type }}"
      volume_size: "{{ volume_size }}"
    instance_tags:
      Name: "{{ my_name }}"
      owner: "{{ owner }}"
      sleep_schedule: "{{ sleep_schedule }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: no
  
  
