---

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "t2.small"
  when: vm_choice == "small (1 vCPU, 2 GiB Memory)"

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "t2.medium"
  when: vm_choice == "medium (2 vCPU, 4 GiB Memory)"

- name: Gather t-shirt size of VM
  set_fact:
    instance_type: "m4.large"
  when: vm_choice == "large (2 vCPU, 8 GiB Memory)"

- name: Launch an AWS EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ my_name }}"
    key_name: "{{ key }}"
    wait: yes
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    region: "{{ region }}"
    security_group: "{{ security_group }}"
    wait: yes
    volumes:
    - device_name: "{{ device_name }}"
      ebs:
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
    tags:
      Name: "{{ my_name }}"
      owner: "{{ owner }}"
      sleep_schedule: "{{ sleep_schedule }}"
    vpc_subnet_id: "{{ subnet_id }}"
    network:
      assign_public_ip: yes

- name: Gather info about instance
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ my_name }}"
  until: ec2_node_info.instances[0].public_ip_address is defined
  delay: 5
  retries: 5
  register: ec2_node_info
    
- name: flatten object
  ansible.builtin.set_fact:
    paths: "{{ lookup('ansible.utils.to_paths', ec2_node_info) }}"
