---

- name: Notify Slack that EC2 instance has been created
  community.general.slack:
    token: "{{ token }}"
    msg: |
        ### EC2 Instance ###
        -----------------------------------
        `Details`: {{ ec2_details }}
        `Name`: {{ paths['instances[0].tags.Name'] }}
        `Public IP`: {{ paths['instances[0].public_ip }}

        Login via:
        ssh -i /path/to/priv-key ec2-user@{{ paths['instances[0].public_ip }}
        -----------------------------------
    channel: '#ansiblefest-demo'
    color: good
    username: 'AnsibleFest-bot'
    link_names: 0
    parse: 'none'


